# Author: NSSA 320 Group 6
# Purpose: Deploy docker stack to main docker server
# Date: 10/24/23
# Version: 1.0

- name: Deploy stack to Docker worker
  hosts: docker_managers
  become: true
  tasks:
    - name: Ensure Git is installed
      ansible.builtin.yum:
        name: git
        state: present

    - name: Download repo
      ansible.builtin.git:
        repo: https://github.com/cnrstvns/nssa-320-final-project
        dest: ~/nssa-320-final-project
        clone: true
        update: true
        force: true

    - name: Download pip
      ansible.builtin.command: curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py

    - name: Install pip
      ansible.builtin.command: python2 get-pip.py

    - name: Install packages
      ansible.builtin.command: pip install jsondiff

    - name: Deploy stack
      docker_stack:
        state: present
        name: web-app
        compose: nssa-320-final-project/app/docker-compose.yml
