# Author: NSSA 320 Group 6
# Purpose: Join Docker worker servers to swarm
# Date: 10/24/23
# Version: 1.0

- name: Join Docker Server to Swarm
  hosts: docker_workers
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.include_tasks:
        file: "install_docker.yml"

    - name: Join Docker Swarm
      ansible.builtin.command: docker swarm join --token SWMTKN-1-3yz3vdxzn5eoxi9fcqxkzxut4hcjtosf0q8moccr8ap8c4gcai-6cdxcwq9mio40mf6p2ux5c5ro 192.168.206.168:3277
