# Author: NSSA 320 Group 6
# Purpose: Join Docker worker servers to swarm
# Date: 10/24/23
# Version: 1.0

- name: Join Docker Server to Swarm
  hosts: docker_workers
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.include_tasks:
        file: "install_docker.yml"

    - name: Join Docker Swarm
      ansible.builtin.command: docker swarm join --token SWMTKN-1-5zlfzdqx7g1axjraozzg3p70vznlj7oedgkexmnhj7z11kmiap-dbwfpob69silktbgmz3pz4n9j 10.116.0.3:2377
