# Author: NSSA 320 Group 6
# Purpose: Join Docker worker servers to swarm
# Date: 10/24/23
# Version: 1.0

- name: Join Docker Server to Swarm
  hosts: docker_workers
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.include_tasks:
        file: "install_docker.yml"

    - name: Join Docker Swarm
      ansible.builtin.command: docker swarm join --token SWMTKN-1-52ckqebbm6t2h9qj2b6p1svv9t1yrm2f4rqnlohxh5j1t5yrnq-07ip4i0s4m9mv9gldfuaonpfd 10.116.0.3:2377
