# Author: NSSA 320 Group 6
# Purpose: Open ports for Docker communication
# Date: 10/25/23
# Version: 1.0

- name: Open ports for Docker communication
  hosts: docker_hosts
  become: true
  tasks:
    - name: Install firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Enable firewalld
      ansible.builtin.service:
        name: firewalld
        enabled: true

    - name: Start firewalld
      ansible.builtin.service:
        name: firewalld
        state: started

    - name: Open ports for Docker
      ansible.builtin.command: "{{ item }}"
      with_items:
        - firewall-cmd --add-port=22/tcp --zone=docker --permanent
        - firewall-cmd --add-port=2376/tcp --zone=docker --permanent
        - firewall-cmd --add-port=2377/tcp --zone=docker --permanent
        - firewall-cmd --add-port=4789/udp --zone=docker --permanent
        - firewall-cmd --add-port=7946/tcp --zone=docker --permanent
        - firewall-cmd --add-port=7946/udp --zone=docker --permanent

    - name: Restart firewalld
      ansible.builtin.command: firewall-cmd --reload
